- src/main/NWNX/API/Events/GoldEvents.cs
I'm bad at branch names. 
But gold events broken out
> Updated gold events

- src/main/NWN/API/Object/NwGameObject.cs
Added these nwscript functions into one getter/setter.
[GetAppearanceType](https://nwnlexicon.com/index.php/GetAppearanceType)
[SetCreatureAppearanceType](https://nwnlexicon.com/index.php?title=SetCreatureAppearanceType)
> CreatureGetAppearanceType

- src/main/NWN/API/Object/NwCreature.cs
[GetCreatureBodyPart](https://nwnlexicon.com/index.php?title=GetCreatureBodyPart)
[SetCreatureBodyPart](https://nwnlexicon.com/index.php?title=SetCreatureBodyPart)
> Added SetCreatureBodyPart GetCreatureBodyPart

- src/main/NWNX/API/Events/StoreEvents.cs
> Use event data 'ITEM' for type NwItem

- .github/workflows/build.yml
- .github/workflows/prbuild.yml
- NWN.Managed.csproj
[Updating to what's new in C# 8.0 and 9.0](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9)
> Dotnet 5 update

- src/main/NWN/API/Object/NwGameObject.cs
- src/main/NWN/API/Object/NwObject.Create.cs
- src/main/NWN/API/Variable/Local/LocalVariable.cs
- src/main/NWN/Services/ScriptDispatch/ScriptCallback.cs
- src/main/NWN/Services/Time/NwDateTime.cs
> Syntax Refactor

- src/main/NWN/API/Object/NwCreature.cs
- src/main/NWN/API/Object/NwDoor.cs
- src/main/NWN/API/Object/NwFaction.cs
- src/main/NWN/API/Object/NwGameObject.cs
- src/main/NWN/API/Object/NwItem.cs
- src/main/NWN/API/Object/NwPlaceable.cs
- src/main/NWN/API/Object/NwPlayer.cs
- src/main/NWN/API/Object/NwStationary.cs
- src/main/NWN/API/Object/NwTrappable.cs
- src/main/NWN/API/Variable/Local/LocalVariable.cs
[Adding functions from this list.](https://github.com/nwn-dotnet/NWN.Managed/issues/27)
> Nwn functions

- src/main/NWN/API/Events/Native/TriggerEvents.cs
- src/main/NWN/API/Object/NwTrigger.cs
https://nwnlexicon.com/index.php/GetClickingObject
> Clicking object

- src/main/NWN/API/Object/NwArea.cs
- src/main/NWNX/API/Area.cs
2 functions from area plugin to export files to the running directory.
> git and are export

- src/main/NWN/API/Events/Native/DoorEvents.cs
> door clicker event

- src/main/NWN/API/Events/Script/SpellEvents.cs
Adding the type of metamagic used to SpellEvents.
> Add MetaMagicFeat to SpellEvents

- src/main/NWN/API/Location/Location.Managed.cs
Sometimes we need to apply an effect at specific location with ApplyEffectAtLocation.
> Adding ApplyEffect to Location

- src/main/NWNX/API/Player.cs
The code looks like it could be generated so that should probably be done at some point (there might already be plans?). I assume manual edits are expected to cover immediate feature needs.
> Map PlayerPlugin.GetBicFileName

- src/main/NWN/API/Location/Location.Managed.cs
> Add multi-type variant for NwLocation->GetObjectsInShape.

- src/main/NWN/API/Color.cs
Completed VGA color list. I personally need YELLOW along with the fixed version of GREEN.
> Expand colors

- src/main/NWN/API/Effect/Effect.Create.cs
Visual effects can now be scaled, rotated, and translated. The PR enables this feature in Managed.
> Add support for VFX transforms

- src/main/NWN/API/Object/NwCreature.cs
- src/main/NWN/API/Object/NwPlayer.cs
FadeFromBlack https://nwnlexicon.com/index.php?title=FadeFromBlack
FadeToBlack https://nwnlexicon.com/index.php?title=FadeToBlack
StopFade https://nwnlexicon.com/index.php?title=StopFade
From issue https://github.com/nwn-dotnet/NWN.Managed/issues/27
I personally need them for something I am doing. Based off of using this as a template.
```
public async Task ClearActionQueue(bool clearCombatState = false)
{
await WaitForObjectContext();
NWScript.ClearAllActions(clearCombatState.ToInt());
}
```
> Fade Functions

- src/main/NWN/API/Constants/GUIPanel.cs
- src/main/NWN/API/Object/NwPlayer.cs
https://nwnlexicon.com/index.php?title=PopUpGUIPanel
https://github.com/nwn-dotnet/NWN.Managed/issues/27
> PopUpGUIPanel

- src/main/NWNX/API/Events/StealthEvents.cs
Changes them to skipable events.
> Update StealthEvents with skipable

- src/main/NWN/API/Location/Location.Managed.cs
Not sure if this is the ideal solution.
> Add is location walkable

- src/main/NWN/API/Object/NwItem.cs
https://discord.com/channels/714927668826472600/714927668826472604/822557315344891944
> changed to bool

- src/main/NWN/API/Object/NwItem.cs
> Add item stack parameter to NwItem.Create

- src/main/NWN/API/Object/NwCreature.cs
- src/main/NWN/API/Object/NwItem.cs
> Add properties for armor check/arcane spell failure. Base AC value

- src/main/NWN/API/Object/NwObject.cs
- src/main/NWN/API/Variable/Campaign/CampaignVariable.cs
- src/main/NWN/API/Variable/Local/LocalVariable.cs
- src/main/NWN/API/Variable/VariableConverterService.cs
> Initialise API dependencies using services.

- NWN.Anvil.csproj.DotSettings
- src/main/Anvil/Internal/EnvironmentConfig.cs
- src/main/NWN/API/Object/NwArea.cs
- src/main/NWN/API/Object/NwObject.cs
- src/main/NWN/Plugins/ITypeLoader.cs
- src/main/NWN/Plugins/Plugin.cs
- src/main/NWN/Plugins/PluginLoader.cs
- src/main/NWN/Services/ResourceManager/ResourceManager.cs
- src/main/NWN/Services/ResourceManager/ResourceNameGenerator.cs
> Resource Manager

- src/main/NWN/API/Events/Native/AssociateEvents/OnAssociateAdd.cs
It builds OK but I've been unable to actually test this on a local instance. If I can get some instructions on how to set up a local dev environment to test the built binary I'll do it, but so far I've been unable to find any documentation on how to contribute.
> Expose AssociateType from OnAddAssociate

- src/main/NWN/API/Object/NwCreature.cs
https://github.com/nwnxee/unified/blob/c54b6db9630068f9691eaecd15fb56e9e99ff581/Plugins/Creature/Creature.cpp#L1126-L1145
> RestoreSpells, RestoreAllSpells

- src/main/NWN/API/Events/Game/PlaceableEvents.cs
> Add ClickedBy property to PlaceableEvents.OnLeftClick

- dockerfile
> add NWN_ANVIL environmental variable

- src/main/NWN/API/Object/NwPlayer.cs
> NwPlayer: Add SpawnLocation.

- src/main/NWN/API/Effect/Effect.Create.cs
> Add effect link functions.

- src/main/NWN/API/Object/NwItem.cs
> Execute "CreateItemOnObject" using module object context.

- src/main/NWN/Services/Events/EventService.EventHandler.cs
- src/main/NWN/Services/GameLoop/LoopService.cs
- src/main/NWN/Services/Scheduler/SchedulerService.cs
- src/main/NWN/Services/ScriptDispatch/DispatchServiceManager.cs
> Catch exceptions in events, loop/scheduler service, dispatch service.

- src/main/NWN/API/Constants/ScriptConstants.cs
- src/main/NWN/API/Events/Game/GameEventFactory.cs
- src/main/NWN/API/Extensions/StringExtensions.cs
- src/main/NWN/API/Object/NwObject.cs
- src/main/NWN/Services/ScriptDispatch/AttributeDispatchService.cs
- src/main/NWNX/Services/NWNXEventFactory.cs
> NwObject: Add Get/SetEventScript.

- src/main/Anvil/API/Object/NwStore.cs
Confirmed OK from `StoreEvents.OnClose`. Let me know if you need anything changed.
> Map NwStore.CurrentCustomers

- NWN.Anvil.csproj.DotSettings
- src/main/Anvil/API/Events/Native/ItemEvents/OnItemScrollLearn.cs
- src/main/Anvil/API/Events/Native/ItemEvents/OnItemUnequip.cs
- src/main/Anvil/API/Events/Native/SkillEvents/OnUseSkill.cs
- src/main/Anvil/API/Object/CreatureLevelInfo.cs
- src/main/Anvil/API/Object/NwCreature.cs
Resolves #342, #343, #344, #345
> Native Events and Functions

- README.md
- src/main/Anvil/Internal/EnvironmentConfig.cs
- src/main/Anvil/Services/LogRedirector/LogMode.cs
- src/main/Anvil/Services/LogRedirector/ServerLogRedirectorService.cs
Adds a server configuration option for redirecting server logs to Anvil/NLog.
> Implement Server Log Redirector Service

- CHANGELOG.md
- src/main/Anvil/API/Constants/EffectRunScriptType.cs
- src/main/Anvil/API/EngineStructure/Effect.Create.cs
- src/main/Anvil/API/Events/Game/AreaOfEffectEvents.cs
- src/main/Anvil/API/Events/Game/GameEventFactory.cs
- src/main/Anvil/API/Events/Script/EffectRunScriptEvent.cs
- src/main/Anvil/API/Extensions/StringExtensions.cs
- src/main/Anvil/API/Object/NwObject.cs
- src/main/Anvil/Services/ScriptDispatch/AttributeScriptDispatchService.cs
- src/main/Anvil/Services/ScriptDispatch/IScriptDispatcher.cs
- src/main/Anvil/Services/ScriptDispatch/RuntimeScriptDispatchService.cs
- src/main/Anvil/Services/ScriptDispatch/ScriptCallbackHandle.cs
- src/main/Anvil/Services/ScriptDispatch/ScriptDispatchService.cs
- src/main/Anvil/Services/ScriptDispatch/ScriptHandleFactory.cs
> Runtime Script Handlers & Effect Action Functions

- CHANGELOG.md
- src/main/Anvil/API/Object/NwPlayer.cs
- src/main/Anvil/Services/Chat/ChatService.cs
> Fix ChatService Target always being null.

- NWN.Anvil.csproj
- dockerfile
- src/main/Anvil/API/Object/EncounterListEntry.cs
- src/main/Anvil/API/Object/EncounterSpawnPoint.cs
- src/main/Anvil/API/Object/NwArea.cs
- src/main/Anvil/API/Object/NwAreaOfEffect.cs
- src/main/Anvil/API/Object/NwCreature.cs
- src/main/Anvil/API/Object/NwDoor.cs
- src/main/Anvil/API/Object/NwEncounter.cs
- src/main/Anvil/API/Object/NwFaction.cs
- src/main/Anvil/API/Object/NwGameObject.cs
- src/main/Anvil/API/Object/NwItem.cs
- src/main/Anvil/API/Object/NwModule.cs
- src/main/Anvil/API/Object/NwObject.cs
- src/main/Anvil/API/Object/NwPlaceable.cs
- src/main/Anvil/API/Object/NwPlayer.cs
- src/main/Anvil/API/Object/NwSound.cs
- src/main/Anvil/API/Object/NwStationary.cs
- src/main/Anvil/API/Object/NwStore.cs
- src/main/Anvil/API/Object/NwTrappable.cs
- src/main/Anvil/API/Object/NwTrigger.cs
- src/main/Anvil/API/Object/NwWaypoint.cs
- src/main/Anvil/API/Utils/NativeUtils.cs
Requires: https://github.com/nwnxee/unified/pull/1441
> Add various encounter properties

- CHANGELOG.md
- NWN.Anvil.Tests/src/main/API/Tlk/StrRefTests.cs
- NWN.Anvil.Tests/src/main/API/Tlk/StrTokenTests.cs
- NWN.Anvil.Tests/src/main/API/TwoDimArray/NwGameTableTests.cs
- NWN.Anvil.Tests/src/main/Generators/Palette.cs
- NWN.Anvil/src/main/API/Object/NwGameObject.cs
- NWN.Anvil/src/main/API/Object/NwPlayer.cs
- NWN.Anvil/src/main/API/Ruleset/NwBaseItem.cs
- NWN.Anvil/src/main/API/Ruleset/NwClass.cs
- NWN.Anvil/src/main/API/Ruleset/NwFeat.cs
- NWN.Anvil/src/main/API/Ruleset/NwSkill.cs
- NWN.Anvil/src/main/API/Ruleset/NwSpell.cs
- NWN.Anvil/src/main/API/Tlk/StrRef.cs
- NWN.Anvil/src/main/API/Tlk/StrTokenCustom.cs
- NWN.Anvil/src/main/API/Tlk/TlkTable.cs
- NWN.Anvil/src/main/Services/ELC/EnforceLegalCharacterService.cs
- NWN.Anvil/src/main/Services/ELC/OnELCValidationFailure.cs
Replaces int/uint references to StrRef with the new structure type.
> Cleanup StrRef API References

- CHANGELOG.md
- NWN.Anvil.Tests/src/main/API/Object/NwCreatureTests.cs
- NWN.Anvil/src/main/API/Object/NwCreature.cs
> Add creature feat use functions + tests.

- NWN.Anvil/src/main/API/Object/NwCreature.cs
- NWN.Anvil/src/main/API/Variable/ObjectStorage/ObjectStorageVariableBool.cs
- NWN.Anvil/src/main/API/Variable/ObjectStorage/ObjectStorageVariableEnum.cs
- NWN.Anvil/src/main/API/Variable/ObjectStorage/ObjectStorageVariableFloat.cs
- NWN.Anvil/src/main/API/Variable/ObjectStorage/ObjectStorageVariableGuid.cs
- NWN.Anvil/src/main/API/Variable/ObjectStorage/ObjectStorageVariableInt.cs
- NWN.Anvil/src/main/API/Variable/ObjectStorage/ObjectStorageVariableString.cs
> Fix Internal Variable Persistence. Fix AlwaysWalk docs

- CHANGELOG.md
- NWN.Anvil/NWN.Anvil.csproj.DotSettings
- NWN.Anvil/src/main/API/Events/Native/MapEvents/OnMapPinAddPin.cs
- NWN.Anvil/src/main/API/Events/Native/MapEvents/OnMapPinChangePin.cs
- NWN.Anvil/src/main/API/Events/Native/MapEvents/OnMapPinDestroyPin.cs
> Add map pin events.

- NWN.Anvil/src/main/API/Object/NwAreaOfEffect.cs
NwAreaOfEffect - Add getters for NwSpell and remaining duration
> NwAreaOfEffect - Add getters for NwSpell and remaining duration

- CHANGELOG.md
- NWN.Anvil/src/main/API/EngineStructure/ItemProperty.Create.cs
- NWN.Anvil/src/main/API/EngineStructure/ItemProperty.cs
- NWN.Anvil/src/main/API/TwoDimArray/Tables/ItemPropertyCostTableEntry.cs
- NWN.Anvil/src/main/API/TwoDimArray/Tables/ItemPropertyCostTablesEntry.cs
- NWN.Anvil/src/main/API/TwoDimArray/Tables/ItemPropertyItemMapTableEntry.cs
- NWN.Anvil/src/main/API/TwoDimArray/Tables/ItemPropertyParamTableEntry.cs
- NWN.Anvil/src/main/API/TwoDimArray/Tables/ItemPropertyParamTablesEntry.cs
- NWN.Anvil/src/main/API/TwoDimArray/Tables/ItemPropertySubTypeTableEntry.cs
- NWN.Anvil/src/main/API/TwoDimArray/Tables/ItemPropertyTableEntry.cs
- NWN.Anvil/src/main/API/TwoDimArray/Tables/NwGameTables.Factory.cs
- NWN.Anvil/src/main/API/TwoDimArray/Tables/NwGameTables.cs
> Implement item property game tables/2das.

- NWN.Anvil/src/main/API/Events/Game/ModuleEvents/ModuleEvents.OnPlayerEquipItem.cs
Due to https://github.com/Beamdog/nwn-issues/issues/464
> Define NwItem Nullable in OnPlayerEquipItem

- NWN.Anvil/src/main/API/Object/NwCreature.cs
- NWN.Anvil/src/main/API/Variable/InternalVariables.cs
- NWN.Anvil/src/main/Services/API/Creature/InitiativeModiferService.cs
- NWN.Anvil/src/main/Services/API/Creature/InitiativeModifierService.cs
Tested all three functions, all work with proper return log. Tested combat initiative rolls, modifier was applied.
Resolves #581
> Added Get/Set/Clear initiative modifier

- NWN.Anvil/src/main/API/Extensions/StringExtensions.cs
> Add "TryParseObject" method to StringExtensions

- NWN.Anvil/src/main/API/Events/Native/ClientEvents/OnPlayerQuickChat.cs
> Add player quick chat event.

- NWN.Anvil/src/main/API/Objects/NwPlayer.cs
- NWN.Anvil/src/main/API/Variables/InternalVariables.cs
- NWN.Anvil/src/main/Services/API/Player/PlayerObjectNameOverrideService.cs
> NwPlayer: Add object name override support.

- NWN.Anvil/src/main/API/Objects/NwPlayer.cs
- NWN.Anvil/src/main/Services/API/Player/PlayerLoopingVisualEffectService.cs
- NWN.Anvil/src/main/Services/API/Player/PlayerObjectNameOverrideService.cs
> Add support for player-specific looping VFX.

- NWN.Anvil.Tests/src/main/API/Objects/NwCreatureTests.cs
- NWN.Anvil/src/main/API/Objects/NwCreature.cs
- NWN.Anvil/src/main/Services/API/Creature/BypassLevelUpValidationService.cs
> NwCreature: Add LevelUp.

- NWN.Anvil/src/main/API/Events/Game/CreatureEvents/CreatureEvents.OnDeath.cs
- NWN.Anvil/src/main/API/Events/Game/GameEventFactory.cs
- NWN.Anvil/src/main/API/Scripts/CallInfo.cs
- NWN.Anvil/src/main/API/Utils/VirtualMachine.cs
- NWN.Anvil/src/main/Services/ScriptDispatch/ScriptHandleResult.cs
Fixes some issues caused by setting the valid property incorrectly.
Does not fix the assertion failure. This will be fixed in the 8193.35 build with: https://github.com/nwnxee/unified/pull/1625
> Make VirtualMachine API more safe. Fix VM issues

- .github/workflows/ci.yml
- NWN.Anvil.Tests/src/docker/docker-compose.yml
- NWN.Anvil.Tests/src/main/System/HttpClientTests.cs
- NWN.Anvil.Tests/src/main/System/WebRequestTests.cs
- dockerfile
Resolves an issue with messed up libssl dependencies in the base NWNX image causing segfaults for https requests in dotnet.
> Create docker image from scratch instead of customizing NWNX image

- NWN.Anvil/src/main/API/EngineStructures/Effect.Create.cs
- NWN.Anvil/src/main/API/Events/Game/AreaOfEffectEvents/AreaOfEffectEvents.OnEnter.cs
- NWN.Anvil/src/main/API/Events/Game/AreaOfEffectEvents/AreaOfEffectEvents.OnExit.cs
- NWN.Anvil/src/main/API/Events/Game/AreaOfEffectEvents/AreaOfEffectEvents.OnHeartbeat.cs
- NWN.Anvil/src/main/API/Events/Game/AreaOfEffectEvents/AreaOfEffectEvents.OnUserDefined.cs
- NWN.Anvil/src/main/API/TwoDimArray/Tables/NwGameTables.Factory.cs
- NWN.Anvil/src/main/API/TwoDimArray/Tables/NwGameTables.cs
- NWN.Anvil/src/main/API/TwoDimArray/Tables/PersistentVfxTableEntry.cs
> Implement PersistentVfxTableEntry.

- NWN.Anvil/src/main/API/Constants/ItemProperty/IPRacialType.cs
- NWN.Anvil/src/main/API/EngineStructures/HitEffect.cs
- NWN.Anvil/src/main/API/EngineStructures/ItemProperty.Create.cs
> Deprecate IPRacialType for NwRace.

- NWN.Anvil/src/main/API/Constants/AddPropPolicy.cs
- NWN.Anvil/src/main/API/Objects/NwItem.cs
> Add ip safe add item property

- NWN.Anvil/src/main/API/EngineStructures/Effect.Create.cs
- NWN.Anvil/src/main/API/Objects/NwGameObject.cs
- NWN.Anvil/src/main/API/Ruleset/NwRace.cs
- NWN.Anvil/src/main/API/Ruleset/NwSpell.cs
- NWN.Anvil/src/main/API/TwoDimArray/Tables/NwGameTables.Factory.cs
- NWN.Anvil/src/main/API/TwoDimArray/Tables/NwGameTables.cs
- NWN.Anvil/src/main/API/TwoDimArray/Tables/PlaceableTypeTableEntry.cs
- NWN.Anvil/src/main/API/TwoDimArray/Tables/PolymorphTableEntry.cs
- NWN.Anvil/src/main/API/TwoDimArray/Tables/PortraitTableEntry.cs
> Add polymorph/portrait/placeable game tables

- NWN.Anvil/src/main/API/Objects/NwCreature.cs
> Return correct type for talent methods.

- NWN.Anvil/src/main/API/Events/Native/DamageEvents/DamageData.cs
Add Custom damage types to DamageData
> Add Custom damage types to DamageData

- NWN.Anvil/src/main/API/Events/Native/DamageEvents/DamageData.cs
- NWN.Anvil/src/main/API/Objects/NwCreature.cs
Expose NwCreature.GetArmorClassVersus()
> Expose NwCreature.GetArmorClassVersus()

- NWN.Anvil/src/main/API/Events/Native/CreatureEvents/OnPolymorphApply.cs
- NWN.Anvil/src/main/API/Events/Native/CreatureEvents/OnPolymorphRemove.cs
- NWN.Anvil/src/main/Native/Functions/Functions.CNWSEffectListHandler.cs
> Add polymorph events.

- NWN.Anvil/src/main/API/Objects/NwPlayer.cs
> Add UpdateCharacterSheet to NwPlayer.

- NWN.Anvil/src/main/API/Nui/NuiWindowEventService.cs
- NWN.Anvil/src/main/AnvilCore.cs
- NWN.Anvil/src/main/Services/ScriptDispatch/AttributeScriptDispatchService.cs
Fixes some edge case issues with hot reload.
> Hot reload fixes

- NWN.Anvil/src/main/API/Objects/NwPlayer.cs
- NWN.Anvil/src/main/API/Variables/InternalVariables.cs
- NWN.Anvil/src/main/Native/Functions/Functions.CNWSCreature.cs
- NWN.Anvil/src/main/Services/API/Player/PlayerPossessionService.cs
> Fix NwPlayer.DMPossessCreature. Add NwPlayer.PlayerPossessCreature

- NWN.Anvil.TestRunner/NWN.Anvil.TestRunner.csproj
- NWN.Anvil.Tests/NWN.Anvil.Tests.csproj
- NWN.Anvil.Tests/NWN.Anvil.Tests.csproj.DotSettings
- NWN.Anvil.Tests/src/main/Services/Core/Hooking/HookServiceTests.cs
- NWN.Anvil/NWN.Anvil.csproj
- NWN.Anvil/src/main/Services/Core/Hooking/FunctionHook.cs
- dockerfile
- docs/NWN.Anvil.Samples.csproj
> Update NWNX/NWN.Core. Fix broken function hooks after dispose.

- NWN.Anvil/src/main/API/Events/Native/ItemEvents/ItemEventHandlerEventFactory.cs
- NWN.Anvil/src/main/API/Events/Native/ItemEvents/ItemHandlerEvent.cs
- NWN.Anvil/src/main/Native/Functions/Functions.CNWSItem.cs
> Add OnItemDecrementStackSize, OnItemDestroy events.

- NWN.Anvil.Tests/src/main/API/Objects/NwAreaTests.cs
- NWN.Anvil.Tests/src/main/API/Objects/NwObjectTests.cs
- NWN.Anvil/src/main/API/Objects/NwArea.cs
- NWN.Anvil/src/main/API/Objects/NwGameObject.cs
> Add Get/Set localized name.

- NWN.Anvil.sln.DotSettings
- NWN.Anvil/src/main/API/Events/Native/ClientEvents/OnPlayerQuickChat.cs
- NWN.Anvil/src/main/API/Events/Native/DMEvents/DMEventFactory.cs
- NWN.Anvil/src/main/API/Events/Native/DebugEvents/DebugEventFactory.cs
- NWN.Anvil/src/main/API/Events/Native/LevelEvents/OnClientLevelUpBegin.cs
- NWN.Anvil/src/main/API/Events/Native/MapEvents/OnMapPinAddPin.cs
- NWN.Anvil/src/main/API/Events/Native/MapEvents/OnMapPinChangePin.cs
- NWN.Anvil/src/main/API/Events/Native/MapEvents/OnMapPinDestroyPin.cs
- NWN.Anvil/src/main/API/Events/Native/PartyEvents/OnPartyEvent.cs
- NWN.Anvil/src/main/API/Utils/NativeUtils.cs
- NWN.Anvil/src/main/Native/Extensions/CNWSMessageExtensions.cs
Reference: https://github.com/nwnxee/unified/pull/1828
> Clear the read message where appropriate to avoid ASSERTing all over the place.

- NWN.Anvil/NWN.Anvil.csproj.DotSettings
- NWN.Anvil/src/main/API/Events/Native/TrapEvents/OnTrapDisarm.cs
- NWN.Anvil/src/main/API/Events/Native/TrapEvents/OnTrapEnter.cs
- NWN.Anvil/src/main/API/Events/Native/TrapEvents/OnTrapExamine.cs
- NWN.Anvil/src/main/API/Events/Native/TrapEvents/OnTrapFlag.cs
- NWN.Anvil/src/main/API/Events/Native/TrapEvents/OnTrapRecover.cs
- NWN.Anvil/src/main/API/Events/Native/TrapEvents/OnTrapSet.cs
- NWN.Anvil/src/main/API/Events/Native/TrapEvents/TrapEvent.cs
- NWN.Anvil/src/main/API/Events/Native/TrapEvents/TrapHookEventFactory.cs
- NWN.Anvil/src/main/Native/Functions/Functions.CNWSCreature.cs
- NWN.Anvil/src/main/Native/Functions/Functions.CNWSTrigger.cs
> Add trap events.

- NWN.Anvil/src/main/API/Events/Native/ItemEvents/OnCreatureAcquireItem.cs
- NWN.Anvil/src/main/Native/Functions/Functions.CNWSCreature.cs
> Add creature acquire item event.
