nwn-dotnet/Anvil

src/main/NWN/API/Object/NwObject.cs, src/main/NWNX/API/Object.cs
Should achieve the desired result of checking if a uuid has been set for an object.
=> correcting uuid check to the nwnx plugin for peekUUID.

src/main/NWN/API/Extensions/StandardFactionExtensions.cs, src/main/NWN/API/Object/NwCreature.cs, src/main/NWN/API/Object/NwFaction.cs, src/main/NWN/API/Object/NwGameObject.cs
Added a nested NwFaction type in NwGameObject that implements faction methods/properties, and a custom IEquatable interface.
For StandardFaction constants, these are implemented as extension methods on the enum.
Usage
**Check if players are in the same party**
```cs
NwPlayer player1;
NwPlayer player2;
if (player1.Faction == player2.Faction)
{
// Player is in same party.
}
```
**Move NPCs to a standard faction**
```cs
NwCreature npc1;
NwCreature npc2;
// Change NPCs to a standard faction.
npc1.ChangeToStandardFaction(StandardFaction.Hostile);
npc2.ChangeToStandardFaction(StandardFaction.Commoner);
```
**Move a NPC to another NPC's faction**
```cs
NwCreature npc1;
NwCreature npc2;
// Change NPC 2 to be the same faction as NPC 1
npc2.Faction = npc1.Faction;
```
**Make a standard faction hate …
=> Faction API

src/main/NWNX/API/Events/ExamineEvents.cs
```
There is a typo in class name. Shouldn't it be OnExamineObjectBefore? https://github.com/nwn-dotnet/NWN.Managed/blob/97cf68e188b0e46a49252729351df5b7647d6bc6/src/main/NWNX/API/Events/ExamineEvents.cs#L10
```
[In regards to this comment in discord](https://discordapp.com/channels/714927668826472600/715651687150518273/773957941987377173)
=> fixed typo

src/main/NWN/API/Object/NwCreature.cs, src/main/NWN/API/Object/NwGameObject.cs
Moving ApplyEffect and RemoveEffect from NwCreature to NwGameObject, so we can apply effect to Doors and Placeables.
=> Move ApplyEffect and RemoveEffect to NwGameObject

src/main/NWN/API/Object/NwPlayer.cs
`PopUpDeathGUIPanel(object, int, int, int, string)`
https://nwnlexicon.com/index.php?title=PopUpDeathGUIPanel
Displays a death panel that can turn off the "Respawn" or "Wait for Help" buttons. The "Wait for Help" button is only enabled when the game is running in multiplayer mode.
By default if sHelpString isn't specified, the value used is "Choose an option below. Respawning will incur a penalty of 50 XP per level of your character and the loss of 10% of your gold." (strref 66219 single player, 6600 for multiplayer).
=> PopUpDeathGUIPanel

src/main/NWN/EnvironmentConfig.cs, src/main/NWN/Plugins/PluginLoader.cs
Adds an option to prevent server startup if no plugins are available to load.
Enable by setting `NWM_PREVENT_START_NO_PLUGIN=true`
=> Add "NWM_PREVENT_START_NO_PLUGIN" option.

src/main/NWN/API/Events/Native/SpellEvents/OnSpellCast.cs, src/main/NWN/Services/ResourceManager/ResourceManager.cs
I assume the property was simply forgotten. Tested OK locally.
=> Expose TargetObject from API.Events.OnSpellCast

NWN.Anvil.csproj.DotSettings, src/main/NWN/API/Constants/CombatMode.cs, src/main/NWN/API/Events/Native/CombatEvents/ForceNewModeOverride.cs, src/main/NWN/API/Events/Native/CombatEvents/OnCombatModeToggle.cs, src/main/NWN/Services/Weapon/DevastatingCriticalData.cs, src/main/NWN/Services/Weapon/MaxRangedAttackDistanceOverride.cs, src/main/NWN/Services/Weapon/WeaponService.cs
Adds the following properties and methods:
```cs
/// <summary>
/// Gets or sets the attack bonus granted to a creature with a "Greater Weapon Focus" feat.<br/>
/// This does not exist in the base game, see <see cref="AddGreaterWeaponFocusFeat"/> to add feats that grant this bonus.
/// </summary>
public int GreaterWeaponFocusAttackBonus { get; set; } = 1;
/// <summary>
/// Gets or sets the damage bonus granted to a creature with a "Greater Weapon Specialization" feat.<br/>
/// This does not exist in the base game, see <see cref="AddGreaterWeaponSpecializationFeat"/> to add feats that grant this bonus.
/// </summary>
public int GreaterWeaponSpecializationDamageBonus { get; set; } = 2;
/// <summary>
/// Gets or sets whether the "Good Aim" feat should also apply to slings.
/// </summary> …
```
=> Implement Weapon Service

src/main/NWN/API/Events/Native/SpellEvents/OnSpellBroadcast.cs, src/main/NWN/API/Events/Native/SpellEvents/OnSpellCast.cs
Considering the object initialization of `Caster = gameObject.ToNwObject<NwCreature>()` I figured these props have the wrong type.
=> Fix upcast of Caster in spell events

src/main/NWN/Services/Dialog/DialogService.cs
Upstream fix shout-out: https://github.com/nwnxee/unified/pull/1360
=> DialogService: Fix a crash when calling CurrentNodeID in an OnConversationAbort event.

src/main/Anvil/AnvilCore.cs, src/main/NWN/API/Events/Game/GameEventFactory.cs, src/main/NWN/API/Events/Native/HookEventFactory.cs, src/main/NWN/API/Object/NwCreature.cs, src/main/NWN/API/Object/NwGameObject.cs, src/main/NWN/API/Object/NwObject.cs, src/main/NWN/API/Object/NwPlayer.cs, src/main/NWN/API/Variable/Campaign/CampaignVariable.cs, src/main/NWN/API/Variable/Local/LocalVariable.cs, src/main/NWN/Services/Chat/ChatService.EventFactory.cs, src/main/NWN/Services/Chat/ChatService.cs, src/main/NWN/Services/ScriptDispatch/AttributeDispatchService.cs, src/main/NWN/Services/Services/AnvilContainerFactory.cs, src/main/NWN/Services/Services/IContainerFactory.cs, src/main/NWN/Services/Services/InjectAttribute.cs, src/main/NWN/Services/Services/InjectPropertyDependencySelector.cs, src/main/NWN/Services/Services/InjectPropertySelector.cs, src/main/NWN/Services/Services/InjectPropertyTypes.cs, src/main/NWN/Services/Services/InjectionService.cs, src/main/NWN/Services/Services/ServiceManager.cs, src/main/NWN/Services/TwoDimArray/TwoDimArrayFactory.cs, src/main/NWNX/Services/NWNXEventFactory.cs
Services can now define their dependencies as properties
- `IInitializable` is an implicit interface that is called once all services have been injected. It does not work on Lazy services.
```cs
[ServiceBinding(typeof(ExampleService))]
public class ExampleService : IInitializable
{
private static readonly Logger Log = LogManager.GetCurrentClassLogger();
[Inject]
private ChatService ChatService { get; init; }
public void Init()
{
ChatService.SetChatHearingDistance(ChatChannel.PlayerWhisper, 50f);
}
}
```
Services can also be injected into runtime created objects:
```cs
[ServiceBinding(typeof(ExampleService))]
public class ExampleService : IInitializable
{
private static readonly Logger Log = LogManager.GetCurrentClassLogger();
[Inject]
private ChatService ChatService { get; init; } …
```
=> Implement property based dependency injection

src/main/Anvil/Services/ObjectStorage/ObjectStorageService.cs
This line spammed my `anvil.log` with multiples of the lines seen below on login. I'm guessing this is leftover debug logs from development.
```log
I [2021/07/13 11:32:29.828] [Anvil.Services.ObjectStorageService]  
I [2021/07/13 11:32:29.828] [Anvil.Services.ObjectStorageService]  
I [2021/07/13 11:32:29.828] [Anvil.Services.ObjectStorageService]  
I [2021/07/13 11:32:29.828] [Anvil.Services.ObjectStorageService]  
I [2021/07/13 11:32:29.828] [Anvil.Services.ObjectStorageService]  
I [2021/07/13 11:32:29.828] [Anvil.Services.ObjectStorageService]  
I [2021/07/13 11:32:29.828] [Anvil.Services.ObjectStorageService]  
I [2021/07/13 11:32:29.828] [Anvil.Services.ObjectStorageService]  
I [2021/07/13 11:32:29.828] [Anvil.Services.ObjectStorageService]  
I [2021/07/13 11:32:29.828] …
```
=> Remove redundant logging

src/main/Anvil/API/Object/NwCreature.cs
`NwCreature` currently offers two ways of getting associates:
* `IEnumerable<NwCreature> Henchmen { get }` yields a list of all henchmen
* `NwCreature GetAssociate(AssociateType associateType() {})` returns a single associate
This makes sense when you consider henchman as the only associate type there can be multiples of. There is however a corner case where a creature can have multiple summons at the moment where a new summon despawns the previous summon on spell cast. This is apparent from the `Area.OnEnter` event where you may loop the number of summoned associates.
As I encounter this corner case while composing a list of all associates of all players in a party, it seems practical to me that Anvil offers this feature. It would certainly save me some time, and possibly others.
As far …
=> Get all creature associates

src/main/Anvil/Plugins/PluginLoadContext.cs
Enables loading plugin `.pdb`s into error contexts, turning
```log
System.NullReferenceException: Object reference not set to an instance of an object.
at BoP.Service.BootsOfTravelService.DoBootsOfTravelEquip(OnPlayerEquipItem onEquip)
at Anvil.Services.EventService.EventHandler`1.TryInvoke(T eventData, Action`1 callback) in /home/runner/work/Anvil/Anvil/src/main/Anvil/Services/Events/EventService.EventHandler.cs:line 57
```
into
```log
System.NullReferenceException: Object reference not set to an instance of an object.
at BoP.Service.BootsOfTravelService.DoBootsOfTravelEquip(OnPlayerEquipItem onEquip) in /home/runner/work/BoP/Service/ItemHandler/BootsOfTravelService.cs:line 21
at Anvil.Services.EventService.EventHandler`1.TryInvoke(T eventData, Action`1 callback) in …
```
=> Fix plugin assemblies not loading on error

src/main/Anvil/AnvilCore.cs, src/main/Anvil/Internal/UnhandledExceptionLogger.cs
Unhandled exceptions are currently consumed by NWNX, and the original stack trace is lost if `stdout` is not observed. Only the native abort signal backtrace is available, which only tells us that the exception came from dotnet:
```
==============================================================
NWNX 8193.26 (01ef335dae) has crashed. Fatal error: Program aborted (6).
Please file a bug at https://github.com/nwnxee/unified/issues
==============================================================
Backtrace:
/nwn/nwnx/NWNX_Core.so(_ZN7NWNXLib8Platform13GetStackTraceB5cxx11Eh+0x3a) [0x7f80726a9c8a]
/nwn/nwnx/NWNX_Core.so(nwnx_signal_handler+0x99) [0x7f8072604579]
/lib/x86_64-linux-gnu/libc.so.6(<UNKNOWN>) [0x7f8072067840]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x10b) [0x7f80720677bb] …
```
=> Log Unhandled Exceptions

src/main/Anvil/API/Events/Game/ModuleEvents.cs
Fixes #336 
Alternatively we can resolve to always use `Item.Possessor`, but I have only tested the login context and can't say anything about other situations.
Consider this merely as a proposal. If you think we're better off not handling this case feel free to close.
=> Patch player reference when null

CHANGELOG.md, NWN.Anvil.csproj.DotSettings, src/main/Anvil/API/Resources/Gff/Fields/GffResourceField.cs, src/main/Anvil/API/Resources/Gff/Fields/GffResourceFieldList.cs, src/main/Anvil/API/Resources/Gff/Fields/GffResourceFieldStruct.cs, src/main/Anvil/API/Resources/Gff/Fields/GffResourceFieldType.cs, src/main/Anvil/API/Resources/Gff/Fields/GffResourceFieldValue.cs, src/main/Anvil/API/Resources/Gff/GffResource.cs, src/main/Anvil/Services/ResourceManager/ResourceManager.cs
Adds support for navigating Gff files in a LINQ-like way (XDocument/JSON.NET).
E.g:
```cs
public GffTest(ResourceManager resourceManager)
{
GffResource palette = resourceManager.GetGenericFile("creaturepalcus", ResRefType.ITP);
Log.Error(palette.FileType);
Log.Error(palette["MAIN"][1]["LIST"][0]["FACTION"]); // Hostile
Log.Error(palette["MAIN"][1]["LIST"][0]["NAME"]); // My Cool Creature
}
```
=> Implement GffResource API

CHANGELOG.md, NWN.Anvil/src/main/API/Object/NwItem.cs
Simple function to return if the baseitem.2da has 1 as the stackable row > 1.
I couldn't think of any edge cases where this could conflict with any custom hak work but definitely wanted to discuss it to make sure.
=> Can Item Stack

NWN.Anvil.Tests/NWN.Anvil.Tests.csproj, NWN.Anvil.Tests/NWN.Anvil.Tests.csproj.DotSettings, NWN.Anvil.Tests/src/main/API/EngineStructure/EffectTests.cs, NWN.Anvil/src/main/API/EngineStructure/Cassowary.cs, NWN.Anvil/src/main/API/EngineStructure/Effect.cs, NWN.Anvil/src/main/API/EngineStructure/EffectBase.cs, NWN.Anvil/src/main/API/EngineStructure/EngineStructure.cs, NWN.Anvil/src/main/API/EngineStructure/Event.cs, NWN.Anvil/src/main/API/EngineStructure/ItemProperty.cs, NWN.Anvil/src/main/API/EngineStructure/Json.cs, NWN.Anvil/src/main/API/EngineStructure/Location.cs, NWN.Anvil/src/main/API/EngineStructure/SQLQuery.cs, NWN.Anvil/src/main/API/EngineStructure/Talent.cs, NWN.Anvil/src/main/API/Events/Native/DamageEvents/OnCreatureAttack.cs, NWN.Anvil/src/main/API/Events/Native/DamageEvents/OnCreatureDamage.cs, NWN.Anvil/src/main/API/Events/Native/EffectEvents/OnCheckEffectImmunity.cs, NWN.Anvil/src/main/API/Events/Native/EffectEvents/OnEffectApply.cs, NWN.Anvil/src/main/API/Events/Native/EffectEvents/OnEffectRemove.cs, NWN.Anvil/src/main/API/Extensions/NativeObjectExtensions.cs
Resolves a rare crash where GC would run despite the object finalizer being suppressed with GC.SuppressFinalize():
```
I [2022/01/03 22:05:53.980] [Anvil.API.Effect] Prevent Gc = True, Running GC on Engine Structure
Constructed from:  at Anvil.API.Effect..ctor(CGameEffect effect, Boolean preventGc)
at Anvil.API.NativeObjectExtensions.ToEffect(CGameEffect effect, Boolean preventGc)
at Anvil.API.Events.OnEffectRemove.Factory.OnEffectRemoved(Void* pEffectListHandler, Void* pObject, Void* pEffect)
I [22:05:53] [NWNX_DotNET] [DotNETExports.cpp:388] Freeing game structure at 0x0x555bab40dba0
NWNX Signal Handler:
==============================================================
NWNX 8193.34 (790a54b734) has crashed. Fatal error: Segmentation fault (11).
Please file a bug at …
```
=> Engine structures: explicitly define memory ownership

CHANGELOG.md, NWN.Anvil/src/main/API/Events/Game/ModuleEvents/ModuleEvents.OnPlayerDeath.cs
I noticed that the `Killer` reference is sometimes `null` and checked what the lexicon says about [GetLastHostileActor(object)](https://nwnlexicon.com/index.php?title=GetLastHostileActor)
> When damage is applied by a placeable using [EffectDamage](https://nwnlexicon.com/index.php?title=EffectDamage), this function returns OBJECT_INVALID, effectively clearing the last creature value. So, for example, on death, if this function returns an invalid creature, you can use [GetLastDamager](https://nwnlexicon.com/index.php?title=GetLastDamager) to identify the killer placeable. It is not known whether this works for traps.
I understand that messing with the Killer reference may be unpopular, but I couldn't find a way to call `GetLastDamager` myself so I cooked up a suggestion. Please let me know …
=> Set PC Killer to LastDamager when LastHostileActor is invalid

NWN.Anvil/src/main/API/EngineStructure/EffectBase.cs, NWN.Anvil/src/main/API/Extensions/IntegerExtensions.cs, NWN.Anvil/src/main/API/Object/CreatureClassInfo.cs, NWN.Anvil/src/main/API/Object/MemorizedSpellSlot.cs, NWN.Anvil/src/main/API/Object/NwCreature.cs, NWN.Anvil/src/main/API/Ruleset/NwRuleset.cs, NWN.Anvil/src/main/API/Ruleset/NwSpell.cs
Speculative fix to resolve `Effect.Spell` returning null in some cases.
=> Fix Spell ID Interpretation

NWN.Anvil/src/main/API/Events/Native/ChatEvents/OnChatMessageSend.cs
I recon this is when nwserver prints `[SERVER]` as the sender's name in game.
=> Define Sender Nullable in OnChatMessageSend

NWN.Anvil/src/main/API/Object/NwArea.cs, NWN.Anvil/src/main/API/TwoDimArray/Tables/LoadScreenTableEntry.cs, NWN.Anvil/src/main/API/TwoDimArray/Tables/NwGameTables.Factory.cs, NWN.Anvil/src/main/API/TwoDimArray/Tables/NwGameTables.cs
Uses a game table entry instead of a numeric index.
=> Implement NwArea.LoadScreen property

NWN.Anvil/src/main/API/Object/NwCreature.cs
I also tried this prop on `NwPlayer`
```cs
public bool IsBartering
{
get => LoginCreature?.Creature.m_pBarterInfo?.m_bWindowOpen.ToBool() == true;
}
```
but it's the same pointer so the shortcut didn't make that much sense to me. Let me know if you need something different.
=> Add NwCreature.IsBartering property

NWN.Anvil/src/main/API/Events/Native/SpellEvents/OnSpellCast.cs
I got nullpointers on these when casting AoE spells, except for `Spell` but I assume that can also be null if the AoE is created without a spell reference. Was the null-forgiving operator used intentionally for some reason?
I also noticed that `Caster` and `Hook` has the null-forgiving operator but removing them has side-effects and I don't know what's correct so I left them alone.
=> Remove null-forgiving operator from OnSpellCast props

NWN.Anvil/src/main/API/Object/NwObject.cs, NWN.Anvil/src/main/API/Object/NwPlayer.cs
Resolves an issue where an exception would be thrown when attempting to remove disconnected/invalid players from a hash-backed collection.
=> Fix object and player hash codes

NWN.Anvil.Tests/src/main/API/EngineStructures/EffectTests.cs, NWN.Anvil/src/main/API/EngineStructures/Effect.cs, NWN.Anvil/src/main/API/EngineStructures/EffectBase.cs, NWN.Anvil/src/main/API/EngineStructures/EngineStructure.cs, NWN.Anvil/src/main/API/EngineStructures/ItemProperty.cs
Fixes an issue where engine structures would never be freed unless explicitly calling `.Dispose()`
=> Fix memory leak with engine structures

NWN.Anvil/src/main/API/Events/Game/GameEventFactory.cs, NWN.Anvil/src/main/API/Utils/VirtualMachine.cs
This fixes an issue where an Event Hook will cause `CallInfo.TryGetEvent()` from a ScriptHandler to fail.
Fixed by preserving EventScriptType in ExecuteScript.
---
Example of a chest with tag `"mychest_tag"` and OnOpen event script `"mychest_onopen"`
```cs
/* Event Hook */
public void Init() {
NwObject.FindObjectsWithTag<NwPlaceable>(
"mychest_tag",
"yourchest_tag",
)
.ToList()
.ForEach(chest => { chest.OnOpen += DoTheFirstThing; });
}
/* Script Handler */
[ScriptHandler("mychest_onopen")]
private void OnOpenMyChest(CallInfo callInfo)
{
if (!callInfo.TryGetEvent<PlaceableEvents.OnOpen>(out var eventData))
{
logger.Error("OnOpenMyChest: Failed to get event data"); // <-- This happens
return;
}
DoTheSecondThing(eventData);
}
```
=> Fix EventScriptType in CallInfo.TryGetEvent

NWN.Anvil/src/main/Services/Core/Logging/UnobservedTaskExceptionLogger.cs, NWN.Anvil/src/main/Services/Services/AnvilServiceManager.cs
Catches and logs uncaught exceptions raised in `async Task` methods, instead of terminating the server.
=> Log unobserved task exceptions instead of terminating.

NWN.Anvil/src/main/API/EngineStructures/ItemProperty.Create.cs
Updated ItemProperty LimitUseByClass to reference the NwClass directly instead of IPClass
=> ItemProperty LimitUseByClass

NWN.Anvil/src/main/Services/ELC/EnforceLegalCharacterService.cs
Throws a validation failure if the PC did not gain an ability point every 4th level
=> ELC validation failure check on 4th level ability gain

NWN.Anvil/src/main/API/EngineStructures/ItemProperty.Create.cs, NWN.Anvil/src/main/API/Objects/NwItem.cs
This PR changes two things:
1. The `durationType` argument to `AddItemProperty` is now correctly evaluated as part of the Add Prop Policy. Without this change it allows duplicates, e.g. when adding Temporary spell effects:
2. The `spellLevel` agument to `OnHitCastSpell` has changed type from `IPSpellLevel` to `int`, to correctly reflect the argument type (ref https://nwnlexicon.com/index.php/ItemPropertyOnHitCastSpell).
(2) introduces a breaking change. I put it in here as I was changing code in this neighborhood, but let me know if you think it belongs in a separate PR and I will move it.
=> Fix poor checks in AddItemProperty

NWN.Anvil/src/main/API/EngineStructures/EffectBase.cs
=> Define EffectBase.Spell as nullable

NWN.Anvil/src/main/API/EngineStructures/Effect.Create.cs
This should resolve issue #772 
No modifications on existing API happens and since the `Effect.Create` has no Unit Tests I didn't add any.
=> Add DamageIncrease method overload to support DamageBonus parameter

NWN.Anvil/src/main/Services/Core/Hooking/FunctionHook.cs, NWN.Anvil/src/main/Services/Core/Hooking/HookService.cs, NWN.Anvil/src/main/Services/Core/Logging/ModuleLoadTracker.cs, NWN.Anvil/src/main/Services/ObjectStorage/ObjectStorageService.cs, NWN.Anvil/src/main/Services/Services/AnvilCoreServiceManager.cs
=> Add persistent function hook methods. Change object storage to core service

NWN.Anvil.Tests/src/main/Services/API/Item/ItemMinEquipLevelOverrideServiceTests.cs, NWN.Anvil/src/main/API/Objects/NwItem.cs, NWN.Anvil/src/main/API/Variables/InternalVariables.cs, NWN.Anvil/src/main/Native/Functions/Functions.CNWSItem.cs, NWN.Anvil/src/main/Services/API/Item/ItemMinEquipLevelOverrideService.cs
=> Add ILR override API/service.
